spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meme_archive?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: meme
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081
